name: impaxt_alert
description: "Call rescued after Impact"
publish_to: 'none'
version: 1.0.0+2
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  supabase_flutter: ^2.9.1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  sensors_plus: ^6.1.1
  geolocator: ^14.0.1
  flutter_background: ^1.3.0+1
  permission_handler: ^12.0.0+1
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.3.0
  url_launcher: ^6.3.1
  sqflite: ^2.4.2
  uuid: ^4.5.1
  flutter_tts: ^4.2.3
  http: ^1.4.0
  speech_to_text: ^7.1.0
  share_plus: ^11.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_launcher_icons: ^0.14.4
  in_app_purchase: ^3.2.3
  flutter_contacts: ^1.1.9+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "images/impaxt_alert.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/impaxt_alert.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/impaxt_alert.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/impaxt_alert.png"
flutter:

  uses-material-design: true
  assets:
    - images/
    - images/impaxt_alert.png
